name: CI Tests

on:
  push:
    paths-ignore: ['**.md']
    branches:
        - main
  pull_request:
    paths-ignore: ['**.md']
    branches:
      - main

jobs:
  # Validate code formatting
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
        shell: bash
      - name: Validate Shell Scripts
        run: |
          mapfile -t scripts < <(find . -iname "*.sh" -or -iname "configure")
          if ! shellcheck "${scripts[@]}"; then
              echo "You must fix shell script issues before submitting a pull request"
              echo ""
              exit 1
          fi
          echo "Your shell scripts are looking real good!"
        shell: bash

  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, kernel: 6.5.0-35-generic, codename: jammy, release: 22.04 }
          - { os: ubuntu-22.04, kernel: 6.8.0-40-generic, codename: jammy, release: 22.04 }
          - { os: ubuntu-24.04, kernel: 6.8.0-41-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.8.0-90-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.14.0-37-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.17.0-14-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.17.0-19-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.17.0-20-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.17.0-22-generic, codename: noble, release: 24.04 }
          - { os: ubuntu-24.04, kernel: 6.8.4-2-pve, codename: pve, release: pve-8.4.0}
          - { os: ubuntu-24.04, kernel: 6.8.12-9-pve, codename: pve, release: pve-8.4.0}

    steps:
      - uses: actions/checkout@v4

      # Install build deps
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc devscripts quilt git flex bison \
              libssl-dev libelf-dev debhelper libncurses-dev gawk openssl \
              dkms libudev-dev libpci-dev libiberty-dev autoconf llvm \
              libdw-dev dwarves libdwarf-dev

          if [[ "${{ matrix.config.codename }}" != "pve" ]]; then
              sudo apt-get install -y \
              linux-headers-${{ matrix.config.kernel }} \
              linux-modules-${{ matrix.config.kernel }}
          fi

          # Enable source repos to get kernel source
          sudo sed -i '/^#\s*deb-src /s/^# *//' /etc/apt/sources.list
          if [[ -f /etc/apt/sources.list.d/ubuntu.sources ]]; then
              sudo sed -Ei 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          fi
          sudo apt-get update
        shell: bash
      - name: Validate Kernel Module Build
        run: |
          # Configure the build with the appropriate kernel version
          KERNEL_VERSION_FULL=${{ matrix.config.kernel }} \
          LSB_CODENAME=${{ matrix.config.codename}} \
          LSB_RELEASE=${{ matrix.config.release}} \
          USE_KERNEL_CONFIG=/usr/src/linux-headers-${{ matrix.config.kernel }}/.config \
          ./configure
          make -j$(nproc) package
        shell: bash
      - name: Archive debian packages
        uses: actions/upload-artifact@v4
        with:
          name: kvm-introvirt-${{ matrix.config.kernel }}.${{ matrix.config.release }}
          path: dist/*.deb
